#!/usr/bin/env python3
"""
Sentiment42 Report Generator
Transforms an AnalysisResult JSON into standalone HTML and Markdown reports.

Usage:
    echo '{"query": "Tesla", ...}' | python3 report-template.py --brand-dir brand-assets --output-dir ~/sentiment-reports

Input:  AnalysisResult JSON from stdin
Output: {query-slug}-{datum}.html and {query-slug}-{datum}.md in output directory

Python stdlib only -- no pip dependencies.
"""

import sys
import json
import base64
import html
import os
import re
import argparse
from pathlib import Path
from datetime import date


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REQUIRED_KEYS = [
    "query", "period", "lang", "total_sources", "total_items",
    "executive_summary", "overall_sentiment", "per_source_sentiment",
    "emotion_profile", "theme_groups", "confidence_assessment",
]

PERIOD_LABELS = {
    "nl": {
        "1m": "Afgelopen maand",
        "3m": "Afgelopen 3 maanden",
        "1y": "Afgelopen jaar",
        "3y": "Afgelopen 3 jaar",
        "5y": "Afgelopen 5 jaar",
    },
    "en": {
        "1m": "Past month",
        "3m": "Past 3 months",
        "1y": "Past year",
        "3y": "Past 3 years",
        "5y": "Past 5 years",
    },
}

# Emotion chart colors -- visually distinct, brand-compatible
EMOTION_COLORS = [
    "#002D49",  # Blue Whale (trust)
    "#FF3349",  # Red Salsa (frustration)
    "#94F200",  # Lime (excitement)
    "#6BDDE0",  # Turquoise Blue (disappointment)
    "#8DB5B4",  # Botticelli (concern)
    "#D2FB50",  # Starship (dynamic 1)
    "#F2A900",  # Amber (dynamic 2)
    "#C77DFF",  # Purple (dynamic 3)
]

# Translations
TR = {
    "nl": {
        "title_prefix": "Sentiment Analyse",
        "summary_heading": "Samenvatting",
        "overall_heading": "Algeheel Sentiment",
        "sources_heading": "Sentiment per Bron",
        "emotions_heading": "Emotie Profiel",
        "themes_heading": "Thema's & Topics",
        "methodology_heading": "Methodologie",
        "positive": "Positief",
        "negative": "Negatief",
        "neutral": "Neutraal",
        "source": "Bron",
        "items": "Items",
        "emotion": "Emotie",
        "percentage": "Percentage",
        "confidence": "Betrouwbaarheid",
        "sources_count": "bronnen uit",
        "platforms": "platforms",
        "date_label": "Datum",
        "core_emotions": "Kernemoties",
        "dynamic_emotions": "Dynamische emoties",
        "dominant_emotions": "Dominante emoties",
        "per_source_leans": "Bronnen",
        "sarcasm_note_label": "Sarcasme",
        "methodology_text": "Analyse uitgevoerd op {datum}. {reasoning}",
        "footer": "Gegenereerd door Sentiment42 | {datum}",
        "stats_heading": "Overzicht",
        "total_sources_label": "Platforms",
        "total_items_label": "Bronnen geanalyseerd",
        "confidence_label": "Betrouwbaarheid",
        "period_label_text": "Periode",
        "sentiment_label": "Sentiment",
    },
    "en": {
        "title_prefix": "Sentiment Analysis",
        "summary_heading": "Summary",
        "overall_heading": "Overall Sentiment",
        "sources_heading": "Sentiment by Source",
        "emotions_heading": "Emotion Profile",
        "themes_heading": "Themes & Topics",
        "methodology_heading": "Methodology",
        "positive": "Positive",
        "negative": "Negative",
        "neutral": "Neutral",
        "source": "Source",
        "items": "Items",
        "emotion": "Emotion",
        "percentage": "Percentage",
        "confidence": "Confidence",
        "sources_count": "sources from",
        "platforms": "platforms",
        "date_label": "Date",
        "core_emotions": "Core Emotions",
        "dynamic_emotions": "Dynamic Emotions",
        "dominant_emotions": "Dominant emotions",
        "per_source_leans": "Sources",
        "sarcasm_note_label": "Sarcasm",
        "methodology_text": "Analysis performed on {datum}. {reasoning}",
        "footer": "Generated by Sentiment42 | {datum}",
        "stats_heading": "Overview",
        "total_sources_label": "Platforms",
        "total_items_label": "Sources analyzed",
        "confidence_label": "Confidence",
        "period_label_text": "Period",
        "sentiment_label": "Sentiment",
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    """Generate URL-safe slug from text."""
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:30]


def load_font_base64(font_path: Path) -> str:
    """Read font file and return base64-encoded string."""
    with open(font_path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def load_svg(svg_path: Path) -> str:
    """Read SVG file and return contents for inline embedding."""
    with open(svg_path, "r", encoding="utf-8") as f:
        return f.read()


def esc(text) -> str:
    """HTML-escape text safely, handling None."""
    if text is None:
        return ""
    return html.escape(str(text))


def confidence_display(conf: str, lang: str) -> str:
    """Translate confidence level."""
    labels = {
        "nl": {"high": "Hoog", "medium": "Gemiddeld", "low": "Laag"},
        "en": {"high": "High", "medium": "Medium", "low": "Low"},
    }
    return labels.get(lang, labels["en"]).get(conf, conf)


def lean_display(lean: str, lang: str) -> str:
    """Translate sentiment lean."""
    labels = {
        "nl": {"positive": "positief", "negative": "negatief", "neutral": "neutraal", "mixed": "gemengd"},
        "en": {"positive": "positive", "negative": "negative", "neutral": "neutral", "mixed": "mixed"},
    }
    return labels.get(lang, labels["en"]).get(lean, lean)


# ---------------------------------------------------------------------------
# Chart.js Config Builders
# ---------------------------------------------------------------------------

def build_overall_chart(data: dict, tr: dict) -> str:
    """Build Chart.js config for overall sentiment stacked horizontal bar."""
    s = data["overall_sentiment"]
    config = {
        "type": "bar",
        "data": {
            "labels": [""],
            "datasets": [
                {"label": tr["positive"], "data": [s["positive"]], "backgroundColor": "#94F200"},
                {"label": tr["negative"], "data": [s["negative"]], "backgroundColor": "#FF3349"},
                {"label": tr["neutral"], "data": [s["neutral"]], "backgroundColor": "#8DB5B4"},
            ],
        },
        "options": {
            "indexAxis": "y",
            "responsive": True,
            "maintainAspectRatio": False,
            "scales": {
                "x": {"stacked": True, "max": 100, "display": False},
                "y": {"stacked": True, "display": False},
            },
            "plugins": {
                "tooltip": {
                    "enabled": True,
                    "callbacks": {"label": "__FUNC_TOOLTIP_PCT__"},
                },
                "legend": {"position": "bottom", "labels": {"font": {"family": "Poppins"}}},
            },
        },
    }
    return _inject_js_functions(json.dumps(config, ensure_ascii=False))


def build_sources_chart(data: dict, tr: dict) -> str:
    """Build diverging horizontal bar for per-source sentiment."""
    sources = data["per_source_sentiment"]
    labels = [s["source_label"] for s in sources]
    neg_data = [-s["sentiment"]["negative"] for s in sources]
    pos_data = [s["sentiment"]["positive"] for s in sources]

    config = {
        "type": "bar",
        "data": {
            "labels": labels,
            "datasets": [
                {"label": tr["negative"], "data": neg_data, "backgroundColor": "#FF3349"},
                {"label": tr["positive"], "data": pos_data, "backgroundColor": "#94F200"},
            ],
        },
        "options": {
            "indexAxis": "y",
            "responsive": True,
            "maintainAspectRatio": False,
            "scales": {
                "x": {
                    "stacked": True,
                    "min": -100,
                    "max": 100,
                    "ticks": {"callback": "__FUNC_ABS_PERCENT__"},
                    "grid": {"color": "#e5e5e5"},
                },
                "y": {"stacked": True, "ticks": {"font": {"family": "Poppins"}}},
            },
            "plugins": {
                "tooltip": {
                    "enabled": True,
                    "callbacks": {"label": "__FUNC_TOOLTIP_ABS_PCT__"},
                },
                "legend": {"position": "bottom", "labels": {"font": {"family": "Poppins"}}},
            },
        },
    }
    return _inject_js_functions(json.dumps(config, ensure_ascii=False))


def build_emotions_chart(data: dict, tr: dict) -> str:
    """Build horizontal bar chart for emotion profile."""
    ep = data.get("emotion_profile", {})
    core = ep.get("core_emotions", [])
    dynamic = ep.get("dynamic_emotions", [])

    labels = [e["label"] for e in core] + [e["label"] for e in dynamic]
    values = [e["percentage"] for e in core] + [e["percentage"] for e in dynamic]
    colors = EMOTION_COLORS[: len(labels)]

    # Separate datasets for core vs dynamic with visual distinction
    config = {
        "type": "bar",
        "data": {
            "labels": labels,
            "datasets": [
                {
                    "label": tr["emotions_heading"],
                    "data": values,
                    "backgroundColor": colors,
                    "borderWidth": 0,
                },
            ],
        },
        "options": {
            "indexAxis": "y",
            "responsive": True,
            "maintainAspectRatio": False,
            "scales": {
                "x": {
                    "max": max(values) + 5 if values else 100,
                    "ticks": {"callback": "__FUNC_PCT_TICK__"},
                    "grid": {"color": "#e5e5e5"},
                },
                "y": {"ticks": {"font": {"family": "Poppins"}}},
            },
            "plugins": {
                "tooltip": {
                    "enabled": True,
                    "callbacks": {"label": "__FUNC_TOOLTIP_PCT__"},
                },
                "legend": {"display": False},
            },
        },
    }
    return _inject_js_functions(json.dumps(config, ensure_ascii=False))


def build_topic_chart(topic: dict, tr: dict, chart_id: str) -> str:
    """Build compact stacked horizontal bar for a topic."""
    s = topic["sentiment"]
    config = {
        "type": "bar",
        "data": {
            "labels": [""],
            "datasets": [
                {"label": tr["positive"], "data": [s["positive"]], "backgroundColor": "#94F200"},
                {"label": tr["negative"], "data": [s["negative"]], "backgroundColor": "#FF3349"},
                {"label": tr["neutral"], "data": [s["neutral"]], "backgroundColor": "#8DB5B4"},
            ],
        },
        "options": {
            "indexAxis": "y",
            "responsive": True,
            "maintainAspectRatio": False,
            "scales": {
                "x": {"stacked": True, "max": 100, "display": False},
                "y": {"stacked": True, "display": False},
            },
            "plugins": {
                "tooltip": {
                    "enabled": True,
                    "callbacks": {"label": "__FUNC_TOOLTIP_PCT__"},
                },
                "legend": {"display": False},
            },
        },
    }
    return _inject_js_functions(json.dumps(config, ensure_ascii=False))


def _inject_js_functions(config_str: str) -> str:
    """Replace placeholder strings with raw JS functions."""
    replacements = {
        '"__FUNC_ABS_PERCENT__"': "function(v) { return Math.abs(v) + '%'; }",
        '"__FUNC_TOOLTIP_PCT__"': "function(ctx) { return ctx.dataset.label + ': ' + ctx.raw + '%'; }",
        '"__FUNC_TOOLTIP_ABS_PCT__"': "function(ctx) { return ctx.dataset.label + ': ' + Math.abs(ctx.raw) + '%'; }",
        '"__FUNC_PCT_TICK__"': "function(v) { return v + '%'; }",
    }
    for placeholder, func in replacements.items():
        config_str = config_str.replace(placeholder, func)
    return config_str


# ---------------------------------------------------------------------------
# HTML Generation
# ---------------------------------------------------------------------------

def generate_html(data: dict, brand_dir: Path, output_path: Path) -> None:
    """Generate standalone HTML report from AnalysisResult."""
    lang = data.get("lang", "nl")
    tr = TR.get(lang, TR["nl"])
    datum = date.today().strftime("%Y-%m-%d")
    period_label = PERIOD_LABELS.get(lang, PERIOD_LABELS["nl"]).get(data["period"], data["period"])

    # Load brand assets
    fonts = {}
    logo_svg = ""
    font_css = ""

    try:
        fonts["poppins_regular"] = load_font_base64(brand_dir / "fonts" / "Poppins-Regular.ttf")
        fonts["poppins_semibold"] = load_font_base64(brand_dir / "fonts" / "Poppins-SemiBold.ttf")
        fonts["poppins_bold"] = load_font_base64(brand_dir / "fonts" / "Poppins-Bold.ttf")
        fonts["lovechild"] = load_font_base64(brand_dir / "fonts" / "Lovechild-Regular.otf")

        font_css = f"""
        @font-face {{
            font-family: 'Lovechild';
            src: url(data:font/otf;base64,{fonts['lovechild']}) format('opentype');
            font-weight: 400;
            font-style: normal;
            font-display: swap;
        }}
        @font-face {{
            font-family: 'Poppins';
            src: url(data:font/ttf;base64,{fonts['poppins_regular']}) format('truetype');
            font-weight: 400;
            font-style: normal;
            font-display: swap;
        }}
        @font-face {{
            font-family: 'Poppins';
            src: url(data:font/ttf;base64,{fonts['poppins_semibold']}) format('truetype');
            font-weight: 600;
            font-style: normal;
            font-display: swap;
        }}
        @font-face {{
            font-family: 'Poppins';
            src: url(data:font/ttf;base64,{fonts['poppins_bold']}) format('truetype');
            font-weight: 700;
            font-style: normal;
            font-display: swap;
        }}
        """
    except FileNotFoundError as e:
        print(f"Warning: Font file not found: {e}. Using fallback fonts.", file=sys.stderr)
        font_css = ""

    try:
        logo_svg = load_svg(brand_dir / "logo-svg" / "chapter42 - color - horizontal.svg")
    except FileNotFoundError:
        print("Warning: Logo SVG not found. Skipping logo.", file=sys.stderr)
        logo_svg = ""

    # Build chart configs
    overall_chart = build_overall_chart(data, tr)
    sources_chart = build_sources_chart(data, tr)
    emotions_chart = build_emotions_chart(data, tr)

    # Build topic charts and cards
    topic_charts_js = []
    topics_html = []
    chart_idx = 0

    for tg in data.get("theme_groups", []):
        theme_name = esc(tg["theme"])
        topic_cards = []

        for topic in tg.get("topics", []):
            chart_id = f"chart-topic-{chart_idx}"
            topic_config = build_topic_chart(topic, tr, chart_id)

            # Build quotes HTML (skip section entirely if no quotes)
            quotes_list = topic.get("quotes") or []
            quotes_html = ""
            for q in quotes_list:
                quote_text = esc(q.get("text", ""))
                source_label = esc(q.get("source_label", ""))
                url = esc(q.get("url", "#"))
                quotes_html += f"""
                <blockquote class="quote">
                    <p>{quote_text}</p>
                    <cite><a href="{url}" target="_blank" rel="noopener">{source_label}</a></cite>
                </blockquote>
                """

            # Build per-source leans
            per_source_html = ""
            for ps in topic.get("per_source", []):
                lean = lean_display(ps.get("sentiment_lean", ""), lang)
                per_source_html += f'<span class="source-lean"><strong>{esc(ps["source_label"])}</strong>: {esc(lean)}</span> '

            # Sarcasm note
            sarcasm_html = ""
            sarcasm = topic.get("sarcasm_note")
            if sarcasm:
                sarcasm_html = f'<p class="sarcasm-note"><em>{tr["sarcasm_note_label"]}: {esc(sarcasm)}</em></p>'

            # Dominant emotions
            dom_emotions = topic.get("dominant_emotions", [])
            dom_html = ""
            if dom_emotions:
                labels = ", ".join(esc(e.get("label", e.get("name", ""))) for e in dom_emotions)
                dom_html = f'<p class="dominant-emotions"><strong>{tr["dominant_emotions"]}:</strong> {labels}</p>'

            # Sentiment text
            s = topic["sentiment"]
            sentiment_text = f'{tr["positive"]}: {s["positive"]}% | {tr["negative"]}: {s["negative"]}% | {tr["neutral"]}: {s["neutral"]}%'

            topic_cards.append(f"""
            <div class="topic-card">
                <h4>{esc(topic["name"])}</h4>
                <p class="topic-sentiment-text">{sentiment_text}</p>
                <div class="chart-container chart-container-topic">
                    <canvas id="{chart_id}"></canvas>
                </div>
                <p class="explanation">{esc(topic.get("explanation", ""))}</p>
                {dom_html}
                <div class="per-source">{per_source_html}</div>
                {sarcasm_html}
                {f'<div class="quotes">{quotes_html}</div>' if quotes_list else ''}
            </div>
            """)

            topic_charts_js.append(
                f"new Chart(document.getElementById('{chart_id}'), {topic_config});"
            )
            chart_idx += 1

        topics_html.append(f"""
        <div class="theme-group">
            <h3>{theme_name}</h3>
            {"".join(topic_cards)}
        </div>
        """)

    # Build stats card (4th grid slot)
    stats_card = f"""
    <div class="chart-card stats-card">
        <h3>{tr["stats_heading"]}</h3>
        <div class="stat-item">
            <span class="stat-value">{data["total_items"]}</span>
            <span class="stat-label">{tr["total_items_label"]}</span>
        </div>
        <div class="stat-item">
            <span class="stat-value">{data["total_sources"]}</span>
            <span class="stat-label">{tr["total_sources_label"]}</span>
        </div>
        <div class="stat-item">
            <span class="stat-value">{confidence_display(data["confidence_assessment"]["overall"], lang)}</span>
            <span class="stat-label">{tr["confidence_label"]}</span>
        </div>
        <div class="stat-item">
            <span class="stat-value">{esc(period_label)}</span>
            <span class="stat-label">{tr["period_label_text"]}</span>
        </div>
    </div>
    """

    # Source quality notes
    quality_notes = data["confidence_assessment"].get("source_quality_notes", [])
    quality_html = ""
    if quality_notes:
        notes_list = "".join(f"<li>{esc(n)}</li>" for n in quality_notes)
        quality_html = f"<ul>{notes_list}</ul>"

    # Methodology text
    methodology_text = tr["methodology_text"].format(
        datum=datum,
        reasoning=esc(data["confidence_assessment"].get("reasoning", "")),
    )

    # Assemble full HTML
    html_content = f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc(tr["title_prefix"])}: {esc(data["query"])}</title>
    <style>
        {font_css}

        *, *::before, *::after {{
            box-sizing: border-box;
        }}

        body {{
            font-family: 'Poppins', sans-serif;
            font-size: 19px;
            line-height: 1.6;
            color: #002D49;
            background: #FFFFFF;
            margin: 0;
            padding: 0;
        }}

        .container {{
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 24px;
        }}

        /* Header */
        header {{
            text-align: center;
            margin-bottom: 48px;
            padding-bottom: 32px;
            border-bottom: 2px solid #F2ECE1;
        }}

        .logo {{
            margin-bottom: 24px;
        }}

        .logo svg {{
            max-width: 200px;
            height: auto;
        }}

        .report-title {{
            font-family: 'Lovechild', serif;
            font-size: 42px;
            font-weight: 700;
            color: #002D49;
            line-height: 1.2;
            margin: 0 0 12px 0;
        }}

        .report-meta {{
            font-size: 15px;
            color: #779A9A;
            margin: 0;
        }}

        /* Section headings */
        h2 {{
            font-family: 'Poppins', sans-serif;
            font-weight: 700;
            font-size: 26px;
            color: #002D49;
            margin: 48px 0 16px 0;
            padding-bottom: 8px;
            border-bottom: 2px solid #F2ECE1;
        }}

        h3 {{
            font-family: 'Poppins', sans-serif;
            font-weight: 600;
            font-size: 22px;
            color: #002D49;
            margin: 32px 0 12px 0;
        }}

        h4 {{
            font-family: 'Poppins', sans-serif;
            font-weight: 600;
            font-size: 19px;
            color: #002D49;
            margin: 0 0 8px 0;
        }}

        /* Executive summary */
        .executive-summary p {{
            font-size: 19px;
            line-height: 1.7;
            color: #002D49;
        }}

        /* Chart grid */
        .chart-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 24px;
            margin: 32px 0;
        }}

        .chart-card {{
            background: #FFFFFF;
            border: 1px solid #e5e5e5;
            border-radius: 3px;
            padding: 20px;
            min-width: 0;
            overflow: hidden;
        }}

        .chart-card h3 {{
            margin: 0 0 16px 0;
            font-size: 18px;
        }}

        .chart-container {{
            position: relative;
            width: 100%;
            max-width: 100%;
            overflow: hidden;
        }}

        .chart-container canvas {{
            max-width: 100%;
        }}

        .chart-container-main {{
            height: 200px;
        }}

        .chart-container-overall {{
            height: 80px;
        }}

        .chart-container-topic {{
            height: 40px;
            margin-bottom: 12px;
        }}

        /* Stats card */
        .stats-card {{
            display: flex;
            flex-direction: column;
            justify-content: center;
            gap: 16px;
            border-radius: 0px;
        }}

        .stat-item {{
            display: flex;
            flex-direction: column;
        }}

        .stat-value {{
            font-weight: 700;
            font-size: 22px;
            color: #002D49;
        }}

        .stat-label {{
            font-size: 14px;
            color: #779A9A;
        }}

        /* Topics */
        .theme-group {{
            margin-bottom: 40px;
        }}

        .topic-card {{
            background: #FFFFFF;
            border: 1px solid #e5e5e5;
            border-radius: 3px;
            padding: 24px;
            margin-bottom: 20px;
        }}

        .topic-sentiment-text {{
            font-size: 14px;
            color: #779A9A;
            margin: 0 0 8px 0;
        }}

        .explanation {{
            font-size: 17px;
            line-height: 1.6;
            color: #002D49;
        }}

        .dominant-emotions {{
            font-size: 15px;
            color: #779A9A;
            margin: 4px 0 8px 0;
        }}

        .per-source {{
            margin: 8px 0;
            font-size: 15px;
            color: #779A9A;
        }}

        .source-lean {{
            display: inline-block;
            margin-right: 16px;
        }}

        .sarcasm-note {{
            font-size: 15px;
            color: #779A9A;
            background: #F2ECE1;
            padding: 8px 12px;
            border-radius: 3px;
            margin: 12px 0;
        }}

        /* Quotes */
        .quote {{
            border-left: 3px solid #FF3349;
            background: #F2ECE1;
            margin: 12px 0;
            padding: 16px 20px;
            border-radius: 0 3px 3px 0;
        }}

        .quote p {{
            font-size: 16px;
            line-height: 1.5;
            color: #002D49;
            margin: 0 0 8px 0;
            font-style: italic;
        }}

        .quote cite {{
            font-size: 14px;
            font-style: normal;
        }}

        .quote cite a {{
            color: #FF3349;
            text-decoration: none;
        }}

        .quote cite a:hover {{
            text-decoration: underline;
        }}

        /* Methodology footer */
        .methodology {{
            margin-top: 64px;
            padding-top: 24px;
            border-top: 2px solid #F2ECE1;
        }}

        .methodology p {{
            font-size: 15px;
            color: #779A9A;
            line-height: 1.6;
        }}

        .methodology ul {{
            font-size: 14px;
            color: #779A9A;
        }}

        .footer-line {{
            text-align: center;
            font-size: 13px;
            color: #779A9A;
            margin-top: 32px;
            padding-top: 16px;
            border-top: 1px solid #e5e5e5;
        }}

        /* Print styles */
        @media print {{
            body {{
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }}
            .chart-container {{
                break-inside: avoid;
                page-break-inside: avoid;
            }}
            .topic-card {{
                break-inside: avoid;
                page-break-inside: avoid;
            }}
            .chart-grid {{
                break-inside: avoid;
            }}
            .quote {{
                break-inside: avoid;
                page-break-inside: avoid;
            }}
        }}

        /* Responsive */
        @media (max-width: 700px) {{
            .container {{
                padding: 20px 16px;
            }}
            .chart-grid {{
                grid-template-columns: 1fr;
            }}
            .report-title {{
                font-size: 28px;
            }}
            .report-meta {{
                font-size: 13px;
            }}
            h2 {{
                font-size: 22px;
                margin: 32px 0 12px 0;
            }}
            h3 {{
                font-size: 19px;
            }}
            .executive-summary p {{
                font-size: 17px;
            }}
            .topic-card {{
                padding: 16px;
            }}
            .quote {{
                padding: 12px 14px;
            }}
            .source-lean {{
                display: block;
                margin-right: 0;
                margin-bottom: 4px;
            }}
            .chart-card {{
                padding: 14px;
            }}
            .chart-card h3 {{
                font-size: 16px;
            }}
            .chart-container-main {{
                height: 180px;
            }}
            .stat-value {{
                font-size: 19px;
            }}
            header {{
                margin-bottom: 32px;
                padding-bottom: 20px;
            }}
            .methodology {{
                margin-top: 40px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">{logo_svg}</div>
            <h1 class="report-title">{esc(tr["title_prefix"])}: {esc(data["query"])}</h1>
            <p class="report-meta">{esc(period_label)} | {data["total_items"]} {tr["sources_count"]} {data["total_sources"]} {tr["platforms"]} | {datum}</p>
        </header>

        <section class="executive-summary">
            <h2>{tr["summary_heading"]}</h2>
            <p>{esc(data["executive_summary"])}</p>
        </section>

        <div class="chart-grid">
            <div class="chart-card">
                <h3>{tr["overall_heading"]}</h3>
                <div class="chart-container chart-container-overall">
                    <canvas id="chart-overall"></canvas>
                </div>
            </div>
            <div class="chart-card">
                <h3>{tr["sources_heading"]}</h3>
                <div class="chart-container chart-container-main">
                    <canvas id="chart-sources"></canvas>
                </div>
            </div>
            <div class="chart-card">
                <h3>{tr["emotions_heading"]}</h3>
                <div class="chart-container chart-container-main">
                    <canvas id="chart-emotions"></canvas>
                </div>
            </div>
            {stats_card}
        </div>

        <section class="topics">
            <h2>{tr["themes_heading"]}</h2>
            {"".join(topics_html)}
        </section>

        <section class="methodology">
            <h2>{tr["methodology_heading"]}</h2>
            <p>{methodology_text}</p>
            {quality_html}
        </section>

        <p class="footer-line">{tr["footer"].format(datum=datum)}</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"></script>
    <script>
        // Overall sentiment chart
        new Chart(document.getElementById('chart-overall'), {overall_chart});

        // Per-source diverging chart
        new Chart(document.getElementById('chart-sources'), {sources_chart});

        // Emotion profile chart
        new Chart(document.getElementById('chart-emotions'), {emotions_chart});

        // Per-topic charts
        {chr(10).join(f"        {tc}" for tc in topic_charts_js)}

        // Print handling
        window.addEventListener('beforeprint', function() {{
            Object.values(Chart.instances).forEach(function(c) {{ c.resize(700, 300); }});
        }});
        window.addEventListener('afterprint', function() {{
            Object.values(Chart.instances).forEach(function(c) {{ c.resize(); }});
        }});
    </script>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)


# ---------------------------------------------------------------------------
# Markdown Generation
# ---------------------------------------------------------------------------

def generate_markdown(data: dict, output_path: Path) -> None:
    """Generate structured Markdown report from AnalysisResult."""
    lang = data.get("lang", "nl")
    tr = TR.get(lang, TR["nl"])
    datum = date.today().strftime("%Y-%m-%d")
    period_label = PERIOD_LABELS.get(lang, PERIOD_LABELS["nl"]).get(data["period"], data["period"])

    lines = []

    # Title and meta
    lines.append(f"# {tr['title_prefix']}: {data['query']}")
    lines.append("")
    lines.append(f"**{tr['period_label_text']}:** {period_label} | **{tr['source']}:** {data['total_items']} {tr['sources_count']} {data['total_sources']} {tr['platforms']} | **{tr['date_label']}:** {datum}")
    lines.append("")

    # Executive summary
    lines.append(f"## {tr['summary_heading']}")
    lines.append("")
    lines.append(data["executive_summary"])
    lines.append("")

    # Overall sentiment
    s = data["overall_sentiment"]
    lines.append(f"## {tr['overall_heading']}")
    lines.append("")
    lines.append(f"| {tr['positive']} | {tr['negative']} | {tr['neutral']} |")
    lines.append("|----------|----------|----------|")
    lines.append(f"| {s['positive']}% | {s['negative']}% | {s['neutral']}% |")
    lines.append("")

    # Per-source sentiment
    lines.append(f"## {tr['sources_heading']}")
    lines.append("")
    lines.append(f"| {tr['source']} | {tr['positive']} | {tr['negative']} | {tr['neutral']} | {tr['items']} | {tr['confidence']} |")
    lines.append("|------|----------|----------|----------|-------|------|")
    for src in data["per_source_sentiment"]:
        ss = src["sentiment"]
        conf = confidence_display(src["confidence"], lang)
        lines.append(f"| {src['source_label']} | {ss['positive']}% | {ss['negative']}% | {ss['neutral']}% | {src['item_count']} | {conf} |")
    lines.append("")

    # Emotion profile
    lines.append(f"## {tr['emotions_heading']}")
    lines.append("")

    # Core emotions (skip table if empty)
    core_emotions = data.get("emotion_profile", {}).get("core_emotions", [])
    if core_emotions:
        lines.append(f"### {tr['core_emotions']}")
        lines.append("")
        lines.append(f"| {tr['emotion']} | {tr['percentage']} |")
        lines.append("|--------|------------|")
        for e in core_emotions:
            lines.append(f"| {e['label']} | {e['percentage']}% |")
        lines.append("")

    # Dynamic emotions
    dynamic = data.get("emotion_profile", {}).get("dynamic_emotions", [])
    if dynamic:
        lines.append(f"### {tr['dynamic_emotions']}")
        lines.append("")
        lines.append(f"| {tr['emotion']} | {tr['percentage']} |")
        lines.append("|--------|------------|")
        for e in dynamic:
            lines.append(f"| {e['label']} | {e['percentage']}% |")
        lines.append("")

    # Themes & Topics
    lines.append(f"## {tr['themes_heading']}")
    lines.append("")

    for tg in data.get("theme_groups", []):
        lines.append(f"### {tg['theme']}")
        lines.append("")

        for topic in tg.get("topics", []):
            lines.append(f"#### {topic['name']}")
            lines.append("")

            ts = topic["sentiment"]
            lines.append(f"**{tr['sentiment_label']}:** {ts['positive']}% {tr['positive'].lower()} / {ts['negative']}% {tr['negative'].lower()} / {ts['neutral']}% {tr['neutral'].lower()}")
            lines.append("")
            lines.append(topic.get("explanation", ""))
            lines.append("")

            # Dominant emotions
            dom = topic.get("dominant_emotions", [])
            if dom:
                labels = ", ".join(e.get("label", e.get("name", "")) for e in dom)
                lines.append(f"**{tr['dominant_emotions']}:** {labels}")
                lines.append("")

            # Per-source leans
            ps_list = topic.get("per_source", [])
            if ps_list:
                leans = ", ".join(
                    f"{ps['source_label']} ({lean_display(ps.get('sentiment_lean', ''), lang)})"
                    for ps in ps_list
                )
                lines.append(f"**{tr['per_source_leans']}:** {leans}")
                lines.append("")

            # Sarcasm note
            sarcasm = topic.get("sarcasm_note")
            if sarcasm:
                lines.append(f"*{tr['sarcasm_note_label']}: {sarcasm}*")
                lines.append("")

            # Quotes
            for q in topic.get("quotes", []):
                lines.append(f"> {q.get('text', '')}")
                lines.append(">")
                lines.append(f"> -- [{q.get('source_label', '')}]({q.get('url', '')})")
                lines.append("")

    # Methodology
    lines.append(f"## {tr['methodology_heading']}")
    lines.append("")
    methodology_text = tr["methodology_text"].format(
        datum=datum,
        reasoning=data["confidence_assessment"].get("reasoning", ""),
    )
    lines.append(methodology_text)
    lines.append("")

    quality_notes = data["confidence_assessment"].get("source_quality_notes", [])
    if quality_notes:
        for note in quality_notes:
            lines.append(f"- {note}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*{tr['footer'].format(datum=datum)}*")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate HTML and Markdown sentiment reports from AnalysisResult JSON.",
    )
    parser.add_argument(
        "--brand-dir",
        required=True,
        help="Path to brand-assets/ directory containing fonts/ and logo-svg/",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Path to output directory for generated reports",
    )
    args = parser.parse_args()

    # Read JSON from stdin
    try:
        raw = sys.stdin.read()
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
        sys.exit(1)

    # Validate required keys
    missing = [k for k in REQUIRED_KEYS if k not in data]
    if missing:
        print(f"Error: Missing required keys in input: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)

    # Resolve paths
    brand_dir = Path(args.brand_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate filenames
    slug = slugify(data["query"])
    datum = date.today().strftime("%Y-%m-%d")
    html_path = output_dir / f"{slug}-{datum}.html"
    md_path = output_dir / f"{slug}-{datum}.md"

    # Generate reports
    generate_html(data, brand_dir, html_path)
    generate_markdown(data, md_path)

    # Output paths
    print(str(html_path))
    print(str(md_path))


if __name__ == "__main__":
    main()
