"""
Similarity Engine — Cosine similarity, component analysis, and clustering.

Supports two modes:
  1. keyword-mapping: keyword vectors × page vectors → best matches per keyword
  2. near-duplicates: page vectors × page vectors → duplicate clusters

Usage:
    python3 similarity.py --mode keyword-mapping --pages pages.npz --keywords kw.npz --output map.json
    python3 similarity.py --mode near-duplicates --data parsed.json --embeddings pages.npz --output clusters.json

Note: numpy .npz files are used for efficient array storage (not pickle).
The allow_pickle=True flag is required by numpy for string arrays stored in .npz format.
All .npz files are generated by our own scripts (sf_parser.py, keyword_embedder.py),
never from untrusted sources.
"""

import argparse
import json
import logging
import re
import sys
from pathlib import Path

import numpy as np

log = logging.getLogger("similarity")


def cosine_similarity_matrix(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Compute cosine similarity between all rows of A and all rows of B.

    Args:
        A: shape (m, d) — e.g., keyword embeddings
        B: shape (n, d) — e.g., page embeddings

    Returns:
        shape (m, n) — similarity scores between -1 and 1

    Efficient for large matrices: uses normalized dot product.
    10k×25k takes ~3 seconds on modern hardware.
    """
    # Normalize rows to unit vectors
    A_norm = A / (np.linalg.norm(A, axis=1, keepdims=True) + 1e-10)
    B_norm = B / (np.linalg.norm(B, axis=1, keepdims=True) + 1e-10)

    # Dot product of normalized vectors = cosine similarity
    return A_norm @ B_norm.T


def url_slug_words(url: str) -> set[str]:
    """Extract meaningful words from a URL path.

    '/commercial-playground-equipment/pricing' → {'commercial', 'playground', 'equipment', 'pricing'}
    Strips protocol, domain, www, TLD, query params, fragments.
    """
    # Remove protocol and domain
    path = re.sub(r"^https?://[^/]+", "", url)
    # Remove query string and fragment
    path = re.split(r"[?#]", path)[0]
    # Split on separators and filter short/common words
    words = re.split(r"[/\-_\.+]", path.lower())
    stop = {"", "www", "com", "net", "org", "html", "htm", "php", "asp", "index", "page", "en", "nl", "de"}
    return {w for w in words if len(w) > 2 and w not in stop}


def url_keyword_boost(keyword: str, url: str, boost: float = 0.05) -> float:
    """Calculate a small boost when keyword words appear in the URL slug.

    Returns a bonus (0 to boost) based on word overlap fraction.
    This is a secondary signal — embedding similarity remains primary.
    """
    kw_words = set(keyword.lower().split())
    slug_words = url_slug_words(url)
    if not kw_words or not slug_words:
        return 0.0
    overlap = len(kw_words & slug_words) / len(kw_words)
    return overlap * boost


def build_reverse_mapping(mappings: list[dict], threshold: float) -> list[dict]:
    """Build reverse view: pages → their mapped keywords.

    Useful for identifying hub pages (pages attracting many keywords)
    and for internal linking strategy.
    """
    page_keywords: dict[str, list[dict]] = {}

    for entry in mappings:
        if entry["classification"] == "gap":
            continue
        for match in entry["matches"]:
            if match["similarity"] >= threshold:
                url = match["url"]
                if url not in page_keywords:
                    page_keywords[url] = []
                page_keywords[url].append({
                    "keyword": entry["keyword"],
                    "similarity": match["similarity"],
                })

    # Sort by keyword count descending
    reverse = []
    for url, keywords in page_keywords.items():
        reverse.append({
            "url": url,
            "keyword_count": len(keywords),
            "keywords": sorted(keywords, key=lambda k: k["similarity"], reverse=True),
        })

    return sorted(reverse, key=lambda p: p["keyword_count"], reverse=True)


def keyword_mapping(
    page_urls: list[str],
    page_embeddings: np.ndarray,
    keywords: list[str],
    keyword_embeddings: np.ndarray,
    threshold: float = 0.70,
    top_n: int = 5,
    url_boost: float = 0.05,
) -> dict:
    """Map keywords to their best matching pages.

    Uses embedding cosine similarity as primary signal, with optional
    URL slug word matching as a secondary boost.

    Returns dict with:
        - mappings: list of {keyword, matches: [{url, similarity, url_boost}]}
        - gaps: keywords with no match above threshold
        - cannibalization: keywords with 2+ pages above threshold
        - reverse_mapping: pages → their mapped keywords (hub page identification)
    """
    log.info(f"Computing similarity matrix ({len(keywords)}×{len(page_urls)})...")
    sim_matrix = cosine_similarity_matrix(keyword_embeddings, page_embeddings)

    mappings = []
    gaps = []
    cannibalization = []

    for i, keyword in enumerate(keywords):
        scores = sim_matrix[i]

        # Apply URL slug boost as secondary signal
        if url_boost > 0:
            boosted_scores = np.array([
                float(scores[j]) + url_keyword_boost(keyword, page_urls[j], url_boost)
                for j in range(len(page_urls))
            ])
        else:
            boosted_scores = scores

        top_indices = np.argsort(boosted_scores)[::-1][:top_n]

        matches = []
        for idx in top_indices:
            embedding_score = float(scores[idx])
            boost_val = float(boosted_scores[idx]) - embedding_score
            combined = float(boosted_scores[idx])
            if combined >= threshold * 0.5:  # Include weaker matches for context
                match_entry = {
                    "url": page_urls[idx],
                    "similarity": round(combined, 4),
                    "embedding_similarity": round(embedding_score, 4),
                }
                if boost_val > 0.001:
                    match_entry["url_boost"] = round(boost_val, 4)
                matches.append(match_entry)

        strong_matches = [m for m in matches if m["similarity"] >= threshold]

        entry = {
            "keyword": keyword,
            "matches": matches,
            "best_match": matches[0] if matches else None,
            "classification": "gap" if not strong_matches else "mapped",
        }

        if not strong_matches:
            gaps.append(entry)
        elif len(strong_matches) >= 2:
            entry["classification"] = "cannibalization"
            cannibalization.append(entry)

        mappings.append(entry)

    # Build reverse mapping: pages → keywords
    reverse = build_reverse_mapping(mappings, threshold)

    result = {
        "total_keywords": len(keywords),
        "total_pages": len(page_urls),
        "mapped": len([m for m in mappings if m["classification"] == "mapped"]),
        "gaps": len(gaps),
        "cannibalization_count": len(cannibalization),
        "mappings": mappings,
        "gap_keywords": gaps,
        "cannibalization_keywords": cannibalization,
        "reverse_mapping": reverse,
        "hub_pages": [p for p in reverse if p["keyword_count"] >= 5],
    }

    log.info(f"Results: {result['mapped']} mapped, {result['gaps']} gaps, "
             f"{result['cannibalization_count']} cannibalization, "
             f"{len(result['hub_pages'])} hub pages (5+ keywords)")
    return result


def near_duplicate_detection(
    page_urls: list[str],
    page_embeddings: np.ndarray,
    threshold: float = 0.85,
    sf_near_dupes: list[dict] | None = None,
    sf_semantic: list[dict] | None = None,
) -> dict:
    """Detect near-duplicate pages using embeddings + SF data.

    Combines:
    1. Embedding cosine similarity (our calculation)
    2. SF MinHash data (if provided)
    3. SF Semantic Similarity data (if provided)
    """
    print(f"Computing pairwise similarity ({len(page_urls)}×{len(page_urls)})...", file=sys.stderr)
    sim_matrix = cosine_similarity_matrix(page_embeddings, page_embeddings)

    # Build SF data lookup
    sf_minhash_lookup = {}
    if sf_near_dupes:
        for entry in sf_near_dupes:
            sf_minhash_lookup[entry["url"]] = entry

    sf_semantic_lookup = {}
    if sf_semantic:
        for entry in sf_semantic:
            sf_semantic_lookup[entry["url"]] = entry

    # Find pairs above threshold
    pairs = []
    n = len(page_urls)
    for i in range(n):
        for j in range(i + 1, n):
            score = float(sim_matrix[i, j])
            if score >= threshold:
                pair = {
                    "url_a": page_urls[i],
                    "url_b": page_urls[j],
                    "embedding_similarity": round(score, 4),
                }

                # Add SF MinHash data if available
                sf_a = sf_minhash_lookup.get(page_urls[i], {})
                if sf_a.get("closest_match") == page_urls[j]:
                    pair["minhash_pct"] = sf_a.get("similarity_pct", 0)

                # Add SF Semantic data if available
                sem_a = sf_semantic_lookup.get(page_urls[i], {})
                if sem_a.get("closest_semantic_match") == page_urls[j]:
                    pair["sf_semantic_score"] = sem_a.get("semantic_score", 0)

                pairs.append(pair)

    # Cluster connected pairs
    clusters = _cluster_pairs(pairs, page_urls)

    # Classify clusters
    for cluster in clusters:
        cluster["classification"] = _classify_cluster(cluster)
        cluster["recommendation"] = _recommend_action(cluster)

    result = {
        "total_pages": n,
        "pairs_above_threshold": len(pairs),
        "clusters": clusters,
        "threshold": threshold,
    }

    print(f"Found {len(pairs)} similar pairs in {len(clusters)} clusters", file=sys.stderr)
    return result


def _cluster_pairs(pairs: list[dict], all_urls: list[str]) -> list[dict]:
    """Group overlapping pairs into clusters using union-find."""
    parent = {url: url for url in all_urls}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for pair in pairs:
        union(pair["url_a"], pair["url_b"])

    # Group by root
    groups = {}
    for pair in pairs:
        root = find(pair["url_a"])
        if root not in groups:
            groups[root] = {"urls": set(), "pairs": []}
        groups[root]["urls"].add(pair["url_a"])
        groups[root]["urls"].add(pair["url_b"])
        groups[root]["pairs"].append(pair)

    clusters = []
    for root, group in groups.items():
        max_sim = max(p["embedding_similarity"] for p in group["pairs"])
        avg_sim = sum(p["embedding_similarity"] for p in group["pairs"]) / len(group["pairs"])

        cluster = {
            "urls": sorted(group["urls"]),
            "size": len(group["urls"]),
            "max_similarity": round(max_sim, 4),
            "avg_similarity": round(avg_sim, 4),
            "pairs": group["pairs"],
        }
        clusters.append(cluster)

    return sorted(clusters, key=lambda c: c["max_similarity"], reverse=True)


def _classify_cluster(cluster: dict) -> str:
    """Classify a cluster based on similarity scores."""
    max_sim = cluster["max_similarity"]
    max_minhash = max((p.get("minhash_pct", 0) for p in cluster["pairs"]), default=0)

    if max_minhash >= 95:
        return "EXACT_DUPLICATE"
    elif max_minhash >= 90:
        return "NEAR_DUPLICATE"
    elif max_sim >= 0.95:
        return "NEAR_DUPLICATE"
    elif max_sim >= 0.85:
        return "SEMANTICALLY_SIMILAR"
    elif max_sim >= 0.70:
        return "THEMATICALLY_RELATED"
    else:
        return "RELATED"


def _recommend_action(cluster: dict) -> str:
    """Generate action recommendation based on classification."""
    recommendations = {
        "EXACT_DUPLICATE": "CANONICAL — Stel canonical in naar de sterkste pagina, redirect de rest met 301",
        "NEAR_DUPLICATE": "MERGE — Combineer content in één pagina, redirect de zwakkere met 301",
        "SEMANTICALLY_SIMILAR": "REVIEW — Controleer of overlap gewenst is. Differentieer titles als ze concurreren",
        "THEMATICALLY_RELATED": "OK — Thematisch verwant is gezond (topic cluster). Geen actie nodig",
        "RELATED": "OK — Gerelateerd maar voldoende uniek",
    }
    return recommendations.get(cluster["classification"], "REVIEW")


def main():
    parser = argparse.ArgumentParser(description="Similarity computation engine")
    parser.add_argument("--mode", required=True, choices=["keyword-mapping", "near-duplicates"])
    parser.add_argument("--pages", help="Page embeddings .npz file")
    parser.add_argument("--keywords", help="Keyword embeddings .npz file (keyword-mapping mode)")
    parser.add_argument("--data", help="Parsed SF data .json file (near-duplicates mode)")
    parser.add_argument("--threshold", type=float, default=0.70, help="Similarity threshold")
    parser.add_argument("--top", type=int, default=5, help="Top N matches per keyword")
    parser.add_argument("--url-boost", type=float, default=0.05, help="URL slug keyword match boost (0 to disable)")
    parser.add_argument("--log-file", help="Write logs to file (in addition to stderr)")
    parser.add_argument("--output", required=True, help="Output JSON file")
    args = parser.parse_args()

    # Configure logging: always stderr, optionally also to file
    handlers = [logging.StreamHandler(sys.stderr)]
    if args.log_file:
        handlers.append(logging.FileHandler(args.log_file, encoding="utf-8"))
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(message)s",
        datefmt="%H:%M:%S",
        handlers=handlers,
    )

    if args.mode == "keyword-mapping":
        if not args.pages or not args.keywords:
            print("ERROR: --pages and --keywords required for keyword-mapping mode", file=sys.stderr)
            sys.exit(1)

        # numpy .npz loading — these files are generated by our own scripts
        pages_data = np.load(args.pages, allow_pickle=True)
        kw_data = np.load(args.keywords, allow_pickle=True)

        page_dim = pages_data["embeddings"].shape[1]
        kw_dim = kw_data["embeddings"].shape[1]

        if page_dim != kw_dim:
            print(f"ERROR: Embedding dimensions don't match! Pages={page_dim}, Keywords={kw_dim}", file=sys.stderr)
            print("Ensure SF and keyword_embedder.py use the same provider and model.", file=sys.stderr)
            sys.exit(1)

        result = keyword_mapping(
            page_urls=list(pages_data["urls"]),
            page_embeddings=pages_data["embeddings"],
            keywords=list(kw_data["keywords"]),
            keyword_embeddings=kw_data["embeddings"],
            threshold=args.threshold,
            top_n=args.top,
            url_boost=args.url_boost,
        )

    elif args.mode == "near-duplicates":
        if not args.pages:
            print("ERROR: --pages required for near-duplicates mode", file=sys.stderr)
            sys.exit(1)

        pages_data = np.load(args.pages, allow_pickle=True)

        sf_near_dupes = None
        sf_semantic = None
        if args.data:
            with open(args.data) as f:
                sf_data = json.load(f)
                sf_near_dupes = sf_data.get("near_duplicates")
                sf_semantic = sf_data.get("semantic_similar")

        result = near_duplicate_detection(
            page_urls=list(pages_data["urls"]),
            page_embeddings=pages_data["embeddings"],
            threshold=args.threshold,
            sf_near_dupes=sf_near_dupes,
            sf_semantic=sf_semantic,
        )

    with open(args.output, "w") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Results saved to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
